mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - "+.local"
    - localhost.ptlogin2.qq.com
  default-nameserver:
    - tls://1.12.12.12
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    'www.google.com': 'https://dns.google/dns-query'      # Google域名使用Google DNS
    'www.facebook.com': 'https://dns.google/dns-query'    # Facebook域名使用Google DNS
    'www.baidu.com': '114.114.114.114'
    '+.internal.crop.com': '10.0.0.1'
    'geosite:cn,private':
    - https://doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://dns.alidns.com/dns-query
  nameserver:
    # 国内DNS服务器
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://doh.sb/dns-query
    - https://dns-unfiltered.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns10.quad9.net/dns-query

    # 国外DNS服务器
    - https://dns.google/dns-query#h3=true             # Google DOH
    - https://cloudflare-dns.com/dns-query#h3=true     # Cloudflare DOH
    - quic://dns.adguard.com:784                       # AdGuard DOQ
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tcp://1.1.1.1
    - https://1.0.0.1/dns-query
    - https://1.1.1.1/dns-query
    - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
