mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - tls://1.1.1.1#\🚀 节点选择
  - tls://8.8.8.8#\🚀 节点选择
  - https://cloudflare-dns.com/dns-query#\🚀 节点选择
  - https://dns.google/dns-query#\🚀 节点选择
  default-nameserver:
  - tls://1.12.12.12
  - 119.29.29.29
  nameserver-policy:
    geosite:cn: https://dns.pub/dns-query
